// Reference data loader for GGUF parity tests
// Loads reference .bin/.npy files generated by llama.cpp or Python scripts

use std::fs::File;
use std::io::Read;
use std::path::Path;

pub struct ReferenceLoader;

impl ReferenceLoader {
    pub fn load_f32_bin(path: &str) -> Option<Vec<f32>> {
        let mut file = File::open(path).ok()?;
        let mut buf = Vec::new();
        file.read_to_end(&mut buf).ok()?;
        
        let len = buf.len() / 4;
        let mut result = Vec::with_capacity(len);
        
        for i in 0..len {
            let bytes: [u8; 4] = buf[i*4..i*4+4].try_into().ok()?;
            result.push(f32::from_le_bytes(bytes));
        }
        
        Some(result)
    }
    
    pub fn load_metadata(path: &str) -> Option<(f32, f32)> {
        let mut file = File::open(path).ok()?;
        let mut content = String::new();
        file.read_to_string(&mut content).ok()?;
        
        let rope_theta = Self::extract_value(&content, "rope_theta");
        let rope_scaling = Self::extract_value(&content, "rope_scaling");
        
        Some((rope_theta, rope_scaling))
    }
    
    fn extract_value(content: &str, key: &str) -> f32 {
        for line in content.lines() {
            if line.contains(key) {
                if let Some(value) = line.split(':').nth(1) {
                    return value.trim().parse().unwrap_or(0.0);
                }
            }
        }
        0.0
    }
    
    pub fn compare_tensors(our: &[f32], ref_data: &[f32]) -> (f32, f32, f32) {
        let min_len = our.len().min(ref_data.len());
        
        let max_abs: f32 = (0..min_len)
            .map(|i| (our[i] - ref_data[i]).abs())
            .fold(0.0f32, f32::max);
        
        let mean_abs: f32 = (0..min_len)
            .map(|i| (our[i] - ref_data[i]).abs())
            .sum::<f32>() / min_len as f32;
        
        let dot_product: f32 = (0..min_len)
            .map(|i| our[i] * ref_data[i])
            .sum();
        
        let norm_a: f32 = (0..min_len)
            .map(|i| our[i] * our[i])
            .sum::<f32>()
            .sqrt();
        
        let norm_b: f32 = (0..min_len)
            .map(|i| ref_data[i] * ref_data[i])
            .sum::<f32>()
            .sqrt();
        
        let cosine = if norm_a > 0.0 && norm_b > 0.0 {
            dot_product / (norm_a * norm_b)
        } else {
            1.0
        };
        
        (max_abs, mean_abs, cosine)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_loader_same_array() {
        let data = vec![1.0f32, 2.0, 3.0, 4.0];
        let (max_abs, mean_abs, cosine) = ReferenceLoader::compare_tensors(&data, &data);
        
        assert!(max_abs < 1e-6);
        assert!(mean_abs < 1e-6);
        assert!((cosine - 1.0).abs() < 1e-6);
    }
}